---
- name: create JBrowse display application directory
  file: path={{galaxy_server_dir}}/display_applications/jbrowse state=directory

- name: place templated jbrowsehub.xml
  template:
    src: 'jbrowsehub.xml.j2'
    dest: "{{galaxy_server_dir}}/display_applications/jbrowse/jbrowsehub.xml"
  when:
   - galaxy_ip_address is defined

- name: place upkeep script
  templace:
    src: 'jbrowse_update.sh.j2'
    dest: "{{galaxy_server_dir}}/display_applications/jbrowse/jbrowse_update.sh"
