---
- name: Ensure /etc/systemd/system/proftpd_script exists
  file: path=/etc/systemd/system/proftpd_script state=directory

- name: Copy configuration script
  copy:
    src: files/masquerade_addr.sh
    dest: /etc/systemd/system/proftpd_script/masquerade_addr.sh
    owner: root
    group: root
    mode: 0544

- name: restart supervisor proftpd
  supervisorctl:
    name: proftpd
    state: restarted
