---
- name: Add a custom /etc/issue login splash screen
  template:
    src: 'issue.j2'
    dest: /etc/issue
  tags:
    - issue_splash_screen
#  copy:
#    src: "{{role_path}}/files/issue"
#    dest: "/etc/issue"
